### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by electricpollution** [jcarolinares/thingiverse_downloader#2]
Downloading newest works fine, but the search seems to be broken.

here is the error I am getting:

Traceback (most recent call last):
  File "thingiverse_downloader.py", line 268, in <module>
    search(args.keywords,args.pages)
  File "thingiverse_downloader.py", line 90, in search
    download_objects(rest_url,str(keywords+".json"));
  File "thingiverse_downloader.py", line 160, in download_objects
    if (len(data_pd)==0):
TypeError: object of type 'NoneType' has no len()

**Comment by jcarolinares** [comment]
Thanks for the issue, just discover myself that something in the thingiverse API has changed. I'm going to take a look.

**Comment by jcarolinares** [comment]
Solved. The official APi has changed the json structure.

Now the search is working. at the commit: https://github.com/jcarolinares/thingiverse_downloader/commit/2597aa41731e842f947df3c33d9fd72f60c5c4db

However there are some problems that I'm not able to find a solution for the user option.
