### ISSUE TITLE
Users option not working

### ISSUE THREAD

**Issue by jcarolinares** [jcarolinares/thingiverse_downloader#3]
When I do a user request I received the following message

{"error":"Login server exception"}

After a careful reading at the API rest documentation I'm not able to find out what is the real problem, the API token is correct and works with other calls and the call seems to be the correct one.

**Comment by xhizorsz** [comment]
For me the user request is working.

**Comment by jcarolinares** [comment]
Hello @xhizorsz Thank you so much for your comment, I've been testing after some months later, and everything seem that is working fine. I'm adding a new option to download the ZIP files that thingiverse offer, which I think coud be useful, you will find it soon.
